### ISSUE TITLE
Can't install from n8n (Version 1.47.3)

### ISSUE THREAD

**Issue by Mikola35** [bramkn/n8n-nodes-run-node-with-credentials#4]
I see this error message:

Error installing new package
Error loading package "n8n-nodes-run-node-with-credentials-x" :The specified package could not be loaded Cause: Cannot find module '/home/node/.n8n/nodes/node_modules/n8n-workflow/dist/index.js'

**Comment by bramkn** [comment]
not sure what you are doing wrong, but here it works on 1.49. 
So seems like something you are not doing right with installing it. Therefore it is not really an issue with the node.

**Comment by bramkn** [comment]
please make sure to put in the right name....
n8n-nodes-run-node-with-credentials-x

**Comment by Mikola35** [comment]
> please make sure to put in the right name.... n8n-nodes-run-node-with-credentials-x

Thanks!
